version: '3.7'

services:
  app:
    build: .
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./initialScript/init.sql:/docker-entrypoint-initdb.d/init.sql
